# Generated by Django 4.1.3 on 2022-11-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_subscribe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscribe",
            old_name="email_name",
            new_name="email",
        ),
    ]
