# Generated by Django 4.1.3 on 2022-11-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_subscribe", "0002_rename_email_name_subscribe_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
