# Generated by Django 4.1.3 on 2022-11-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_subscribe", "0003_alter_subscribe_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribe",
            name="option",
            field=models.CharField(
                choices=[("W", "Weekly"), ("M", "Monthly")], default="W", max_length=2
            ),
        ),
    ]
