# Generated by Django 4.1.3 on 2022-11-11 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2022, 11, 11, 16, 27, 32, 501032, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobpost",
            name="description",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobpost",
            name="salary",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
