# Generated by Django 4.1.3 on 2022-11-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0003_jobpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="slug",
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
