# Generated by Django 4.1.3 on 2022-11-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0004_alter_jobpost_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="expiry",
            field=models.DateField(null=True),
        ),
    ]
