# Generated by Django 4.1.3 on 2022-11-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0007_author_jobpost_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="jobpost",
            name="skills",
            field=models.ManyToManyField(null=True, to="app_one.skill"),
        ),
    ]
