# Generated by Django 4.1.3 on 2022-11-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0009_alter_jobpost_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
