# Generated by Django 4.1.3 on 2022-11-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_one", "0011_jobpost_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpost",
            old_name="type",
            new_name="job_type",
        ),
    ]
