# Generated by Django 4.1.3 on 2022-11-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_upload", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upload",
            old_name="image_url",
            new_name="image",
        ),
    ]
